import { motion } from "framer-motion";
import Head from "next/head";
import { useRouter } from "next/router";
import MainContainer from "../../components/profilePage/MainContainer";

export default function Page() {
  const router = useRouter();
  const id = router.query.slug?.toString();

  return (
    <motion.div
      initial={{ opacity: 0 }}
      whileInView={{ opacity: 1 }}
      viewport={{ once: true }}
    >
      <Head>
        <title>Profile</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/images/header.png" />
      </Head>
      {id ? <MainContainer slug={id} /> : <div>Đang tìm kiếm</div>}
    </motion.div>
  );
}
