import { Box, Button, Divider, Select, Text } from "@chakra-ui/react";
import { motion } from "framer-motion";
import Head from "next/head";
import React, { useEffect, useState } from "react";
import { useAuthState } from "react-firebase-hooks/auth";

import About from "../../components/Community/About";
import PageContent from "../../components/Layout/PageContent";
import NewPostForm from "../../components/posts/NewPostForm";
import { auth } from "../../firebase/clientApp";
import useCommunityData from "../../hooks/useCommunityData";
import EditorLarge from "@/components/editor/EditorLarge";
import { useSelector } from "react-redux";
import { RootState } from "@/redux/store";
import Rule from "@/components/Community/Rule";
import { postingGroup } from "../../../apis/posts";
import { useRouter } from "next/router";
import EditorNormal from "@/components/editor/EditorNormal";
type Posting = {
  content: string;
  time: Date;
  userId: number;
  groupId: number;
  titles: string;
}

const Page: React.FC = () => {
  const user = useSelector((state: RootState) => state.userInfor.currentUser);
  const [htmlString, setHtmlStringg] = useState<string>("");
  const { communityStateValue } = useCommunityData();
  const [group, setGroup] = useState(-1);
  const router = useRouter();
  const handlePost = async () => {
    if (group == -1 || group == 0) return;
    try {
      let post: Posting = {
        content: htmlString,
        time: new Date,
        userId: user.userId,
        groupId: group,
        titles: ""
      }
      console.log("post data" + post.content);

      await postingGroup(post);
      router.push(`/group/${group}`);

    } catch (error) {
      console.log(error);

    }

  }

  useEffect(() => {
    console.log(group);
    console.log("strinsadasdada" + htmlString);

  }, [group])
  return (
    <motion.div
      initial={{ opacity: 0 }}
      whileInView={{ opacity: 1 }}
      viewport={{ once: true }}
    >
      <Head>
        <title>Reddit Clone</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/images/header.png" />
      </Head>
      <PageContent>
        <div className="w-[100%]">

          {/* {mySnippets && } */}

          <Select placeholder='Select option' background={"whiteAlpha.800"} fontStyle={"bold"} onChange={(e) => setGroup(Number(e.target.value))}>
            {communityStateValue.mySnippets.map((snippet) => (
              <option value={snippet.groupId}> Group : {snippet.groupName}</option>
            ))}
          </Select>
          {user && (
            <> <EditorLarge formTitle=""
              htmlString={htmlString}
              setHtmlString={setHtmlStringg}
              pageName="create_blog"></EditorLarge>
              {/* <EditorNormal
                htmlString={htmlString}
                setHtmlString={setHtmlStringg}
                useEditorFor="create_blog" isNeedSave={false}></EditorNormal> */}
            </>

          )}
        </div>
        <div className="flex flex-col fixed ">
          <Rule />
          <Divider />
          <Button colorScheme='teal' variant='solid' disabled={group == -1 || group == 0 ? true : false} onClick={() => handlePost()}>
            {group == -1 || group == 0 ? "Hãy chọn group" : "Đăng ngay"}
          </Button>
        </div>
      </PageContent>
    </motion.div>
  );
};
export default Page;
