import { motion } from "framer-motion";
import Head from "next/head";
import { useState } from "react";

import EditorLarge from "@/components/editor/EditorLarge";

export default function Page() {
  const [htmlString, setHtmlStringg] = useState<string>("");
  return (
    <motion.div
      initial={{ opacity: 0 }}
      whileInView={{ opacity: 1 }}
      viewport={{ once: true }}
    >
      <Head>
        <title>Tạo bài viết</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/images/header.png" />
      </Head>

      <EditorLarge
        formTitle=""
        htmlString={htmlString}
        setHtmlString={setHtmlStringg}
        pageName="create_blog"
      ></EditorLarge>
    </motion.div>
  );
}
