'use client'
import { motion } from "framer-motion";
import Head from "next/head";



interface DataType {
  documentName: string;
  description: string;
  cost: number;
  time: Date;
  group: string;
  message: string;
}

export default function Page() {
 
  return (
    <motion.div
      initial={{ opacity: 0 }}
      whileInView={{ opacity: 1 }}
      viewport={{ once: true }}
    >
      <Head>
        <title>Camp Scholar</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/images/header.png" />
      </Head>
      <div>ho</div>
    </motion.div>
  );
}
